name: Frontend CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm' # Use npm for caching

      # Install dependencies
      - name: Install Dependencies
        run: npm ci # Use npm ci for consistent installs

      # Build Next.js app
      - name: Build
        run: npm run build

      # Run tests (uncomment if needed)
      # - name: Test
      #   run: npm test
      #   if: ${{ success() }} # Only run tests if build succeeds

      # Deploy to Vercel
      - name: Deploy to Vercel
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' # Fixed to master
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $VERCEL_TOKEN" \
            -d '{"gitSource": {"type": "github", "repoId": "${{ secrets.REPO_ID_GITHUB }}", "ref": "master"}}' \
            https://api.vercel.com/v13/deployments